name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: composer:v2

      - name: Build
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: flywp
          VERSION: ${{ github.event.inputs.tag }}

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          MSG_MINIMAL: true
          SLACK_CHANNEL: "flywp-ops"
          SLACK_ICON: https://github.com/flywp.png?size=48
          SLACK_TITLE: FlyWP Helper
          SLACK_USERNAME: flybot
          SLACK_MESSAGE: "New version deployed to WordPress.org: ${{ github.event.inputs.tag }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
